export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const INCREMENT_NUMBER = 'INCREMENT_NUMBER';
export const DECREMENT_NUMBER = 'DECREMENT_NUMBER';

export const GET_DATA = 'GET_DATA';